"""Which request fixture goes to which route, and what response is expected.

`tests/fixtures/manifest.json` maps a fixture to a schema name -- it does not
say which route sends or receives it (T-178 was deliberately silent on that;
see `docs/contracts/dependent-notes.md`). This module is the one place that
makes that pairing explicit, by hand, once, so both the fixture-replay stub
and the live-server harness agree on it.

Four response schemas (`Ticket`, `Agent`, `Review`, `Member`, `Channel`) have
no dedicated fixture -- they only appear nested inside a screen fixture. Those
cases use `FixtureRef.extract` instead of inventing new example JSON.

PROJECT_ID and the other sample ids below are drawn from the fixtures
themselves (e.g. `tests/fixtures/tickets/detail-claimed.json` uses
`DEMO-13` / `prj_demo0001`) purely so a human reading a request log sees
consistent ids; the stub does not check referential integrity between them.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .fixtures import FixtureRef

PROJECT_ID = "prj_demo0001"
TICKET_ID = "DEMO-13"
AGENT_ID = "agt_backend01"
CHANNEL_ID = "chn_work0001"
MESSAGE_ID = "msg_00000001"
RUN_ID = "run_00000005"
REVIEW_ID = "rev_00000002"
RUNNER_ID = "rnr_00000001"


@dataclass(frozen=True)
class Case:
    operation_id: str
    variant: str  # distinguishes multiple fixtures against the same route
    request: FixtureRef | None
    response: FixtureRef
    path_values: dict = field(default_factory=dict)
    query_values: dict = field(default_factory=dict)

    @property
    def label(self) -> str:
        return self.operation_id if self.variant == "default" else f"{self.operation_id}[{self.variant}]"


def _ref(rel_path: str, *extract: object) -> FixtureRef:
    return FixtureRef(rel_path, tuple(extract))


# ------------------------------------------------------------- read screens
# GET routes: no request body, so only the success + schema checks apply.

READ_CASES = [
    Case("getOverview", "default", None, _ref("overview/populated.json")),
    Case("listTickets", "default", None, _ref("tickets/list-populated.json")),
    Case("getTicket", "default", None, _ref("tickets/detail-claimed.json"),
         path_values={"ticket_id": TICKET_ID}),
    Case("listAgents", "default", None, _ref("agents/list-populated.json")),
    Case("getMasterPanel", "default", None, _ref("master/panel-active.json")),
    Case("listActivity", "default", None, _ref("activity/populated.json")),
    Case("listMembers", "default", None, _ref("messages/members.json")),
    Case("listChannels", "default", None, _ref("messages/channels-populated.json")),
    Case("listMessages", "default", None, _ref("messages/list-populated.json"),
         query_values={"channel_id": CHANNEL_ID}),
    Case("listDeliveries", "default", None, _ref("messages/deliveries-receipt-chain.json"),
         path_values={"message_id": MESSAGE_ID}),
    Case("listWakeJobs", "default", None, _ref("runners/jobs-populated.json"),
         query_values={"runner_id": RUNNER_ID}),
    # streamEvents is text/event-stream, not a single JSON response -- a
    # different protocol than the rest of this harness checks. Out of scope
    # here; T-185 covers live SSE behaviour against the real server.
]

# ------------------------------------------------------------------ mutations
# Every one of these also gets an actor-rejection variant generated by the
# harness (frozen decision 1): the same body plus a top-level "actor" field
# must be refused 400 `malformed_request`.

MUTATION_CASES = [
    Case("createTicket", "default", _ref("tickets/request-create.json"),
         _ref("tickets/detail-claimed.json", "ticket")),
    Case("claimTicket", "default", _ref("tickets/request-claim.json"),
         _ref("tickets/detail-claimed.json", "ticket"),
         path_values={"ticket_id": TICKET_ID}),
    Case("createTicketUpdate", "default", _ref("tickets/request-update.json"),
         _ref("tickets/detail-claimed.json", "updates", 0),
         path_values={"ticket_id": TICKET_ID}),
    Case("requestReview", "default", _ref("tickets/request-review.json"),
         _ref("tickets/detail-review-pending.json", "reviews", 0),
         path_values={"ticket_id": TICKET_ID}),
    Case("decideReview", "accept", _ref("tickets/request-review-accept.json"),
         _ref("tickets/detail-review-pending.json", "reviews", 0),
         path_values={"ticket_id": TICKET_ID, "review_id": REVIEW_ID}),
    Case("decideReview", "reject", _ref("tickets/request-review-reject.json"),
         _ref("tickets/detail-review-pending.json", "reviews", 0),
         path_values={"ticket_id": TICKET_ID, "review_id": REVIEW_ID}),
    Case("setTicketBlocked", "default", _ref("tickets/request-set-blocked.json"),
         _ref("tickets/detail-blocked.json", "ticket"),
         path_values={"ticket_id": TICKET_ID}),
    Case("revokeSessionLease", "default", _ref("agents/request-revoke-lease.json"),
         _ref("agents/list-populated.json", "items", 0),
         path_values={"agent_id": AGENT_ID}),
    Case("createEnrollment", "default", _ref("agents/request-enrollment.json"),
         _ref("agents/response-enrollment.json")),
    Case("exchangeEnrollment", "default", _ref("agents/request-session-exchange.json"),
         _ref("agents/response-session-credential.json")),
    Case("postHookEvent", "event", _ref("hooks/request-event.json"),
         _ref("hooks/response-accepted.json")),
    Case("postHookEvent", "with-note", _ref("hooks/request-event-with-note.json"),
         _ref("hooks/response-accepted.json")),
    Case("postHookEvent", "stop", _ref("hooks/request-event-stop.json"),
         _ref("hooks/response-accepted.json")),
    Case("takeMasterLease", "default", _ref("master/request-lease.json"),
         _ref("master/response-lease.json")),
    Case("setMasterPaused", "default", _ref("master/request-pause.json"),
         _ref("master/response-lease.json")),
    Case("createAssignment", "default", _ref("master/request-assignment.json"),
         _ref("master/response-assignment-queued.json")),
    Case("createInvitation", "default", _ref("messages/request-invitation.json"),
         _ref("messages/response-invitation.json")),
    Case("exchangeInvitation", "default", _ref("messages/request-invitation-exchange.json"),
         _ref("messages/members.json", "items", 0)),
    Case("createChannel", "default", _ref("messages/request-create-channel.json"),
         _ref("messages/channels-populated.json", "items", 0)),
    Case("addChannelMember", "default", _ref("messages/request-add-channel-member.json"),
         _ref("messages/response-channel-member.json"),
         path_values={"channel_id": CHANNEL_ID}),
    Case("sendMessage", "default", _ref("messages/request-send.json"),
         _ref("messages/response-send.json")),
    Case("sendTask", "direct", _ref("messages/request-task-direct.json"),
         _ref("messages/response-task-dispatched.json"),
         path_values={"message_id": MESSAGE_ID}),
    Case("sendTask", "via-master", _ref("messages/request-task-via-master.json"),
         _ref("messages/response-task-dispatched.json"),
         path_values={"message_id": MESSAGE_ID}),
    Case("registerRunner", "default", _ref("runners/request-register.json"),
         _ref("runners/response-runner-lease.json")),
    Case("postRunEvent", "started", _ref("runners/request-run-event-started.json"),
         _ref("runners/response-run-failed.json"),
         path_values={"run_id": RUN_ID}),
    Case("postRunEvent", "needs-approval", _ref("runners/request-run-event-needs-approval.json"),
         _ref("runners/response-run-paused-approval.json"),
         path_values={"run_id": RUN_ID}),
    Case("postRunEvent", "budget-reached", _ref("runners/request-run-event-budget-reached.json"),
         _ref("runners/response-run-budget-paused.json"),
         path_values={"run_id": RUN_ID}),
    Case("cancelRun", "default", _ref("runners/request-cancel.json"),
         _ref("runners/response-run-failed.json"),
         path_values={"run_id": RUN_ID}),
]

ALL_CASES = READ_CASES + MUTATION_CASES
