"""Safe identity boundaries for generated wrappers and inherited hooks."""
from __future__ import annotations

import copy
import os
import re
import shlex
import uuid

PROVIDER_SESSION_ID_VARS = (
    "TICKET_SESSION_ID", "CLAUDE_CODE_SESSION_ID", "CODEX_SESSION_ID",
    "CURSOR_SESSION_ID", "TERM_SESSION_ID", "CURSOR_CONVERSATION_ID",
)


def remote_wrapper(script, board, owner, prompt_kind=""):
    """Render an owner-bound session distinct from the installer's session."""
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]{0,100}", owner or ""):
        raise ValueError("wrapper needs a unique valid agent id")
    sid = "wrapper:%s:%s" % (owner, uuid.uuid4().hex)
    executable = shlex.quote(os.path.realpath(script))
    prompt = " --prompt-kind " + shlex.quote(prompt_kind) if prompt_kind else ""
    return """#!/bin/sh
# Generated by tickets hooks remote. Identity belongs to this wrapper.
unset %s
export TICKET_AGENT=%s
export TICKET_SEAT=%s
export TICKET_SESSION_ID=%s
export TICKETS_DIR=%s
if [ "$#" -eq 0 ]; then
  exec %s hook-run --agent %s --event task-wake%s
fi
exec %s "$@"
""" % (" ".join(PROVIDER_SESSION_ID_VARS), shlex.quote(owner), shlex.quote(owner),
       shlex.quote(sid), shlex.quote(os.path.abspath(board)), executable,
       shlex.quote(owner), prompt, executable)


def is_board_hook(command):
    """Recognize Atman lifecycle hooks, leaving unrelated commands intact."""
    text = str(command or "")
    try:
        words = shlex.split(text)
    except ValueError:
        words = []
    for index, word in enumerate(words[:-1]):
        if os.path.basename(word) not in ("tickets", "tickets.py", "atm", "atm.py"):
            continue
        operation = words[index + 1]
        if operation in ("hook-run", "codex-hook", "stop-hook"):
            return True
        assigned = "TICKET_AGENT=" in text or "TICKET_SEAT=" in text
        if operation == "inbox" and (assigned or "--keep" in words[index + 2:]):
            return True
        if assigned and operation in ("board", "identity", "join", "next", "msg", "review", "update"):
            return True
    return any(marker in text for marker in ("tickets-board.py", "check-message-board.py"))


def without_board_hooks(settings):
    """Copy Claude settings, filtering individual Atman commands in entries."""
    result = copy.deepcopy(settings)
    hooks = result.get("hooks") if isinstance(result, dict) else None
    if not isinstance(hooks, dict):
        return result, False
    changed = False
    for event, entries in list(hooks.items()):
        if not isinstance(entries, list):
            continue
        kept = []
        event_changed = False
        for entry in entries:
            commands = entry.get("hooks") if isinstance(entry, dict) else None
            if not isinstance(commands, list):
                kept.append(entry)
                continue
            clean = [command for command in commands if not (
                isinstance(command, dict) and is_board_hook(command.get("command")))]
            if len(clean) == len(commands):
                kept.append(entry)
                continue
            event_changed = changed = True
            if clean:
                entry["hooks"] = clean
                kept.append(entry)
        if event_changed:
            if kept:
                hooks[event] = kept
            else:
                hooks.pop(event, None)
    return result, changed
