exec(open('/tmp/t976-final-probes/t976_journeys.py').read().split("for name,fn in [('normal'")[0])
ENV.pop('PYTEST_CURRENT_TEST',None)
ENV['PATH']='/tmp/atman-t976-0923-bin:'+os.path.expanduser('~/.local/bin')+':/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin'
repo=setup('live');w=worktree(repo,'live-codex')
atm(w,'join','live-codex','--roles','liveprobe','--harness','codex','--persistent','--wake-mode','continuous',agent='live-codex')
atm(w,'inbox',agent='live-codex')
(ROOT/'location.json').write_text(json.dumps({'repo':str(repo),'worktree':str(w)}))
pathlib.Path('/tmp/t976-live-location').write_text(str(ROOT))
e=dict(ENV,TICKET_AGENT='live-codex'); log=open(ROOT/'wake-watch.log','w')
p=subprocess.Popen([ATM,'watch','--agent','live-codex','--cwd',str(w),'--every','1','--max-runs','1','--run-timeout','3'],cwd=w,env=e,stdout=log,stderr=log,start_new_session=True)
(ROOT/'watch.pid').write_text(str(p.pid));time.sleep(3)
r=atm(repo,'msg','LIVE WAKE PROBE nonce t976-0923-wake: read this inbox and reply using atm msg --to boss with exactly ACK t976-0923-wake. No ticket is ready yet; stop after this receipt.','--to','live-codex')
print('ROOT',ROOT,'PID',p.pid,r.stdout,flush=True)
try:p.wait(timeout=160)
except subprocess.TimeoutExpired:os.killpg(p.pid,signal.SIGTERM);p.wait(timeout=15)
log.close();print('exit',p.returncode,flush=True);print(atm(repo,'inbox').stdout,flush=True)
